language: python
python:
  - "2.7"
sudo: false
addons:
  apt:
    sources:
    - python-yaml
    - python-pygame
install:
  - pip install webcolors
  - wget https://github.com/smathot/python-yamldoc/archive/release/0.2.0.tar.gz -O yamldoc.tar.gz
  - tar -xzvf yamldoc.tar.gz
  - export PYTHONPATH=$PYTHONPATH:python-yamldoc-release-0.2.0
script: ./run_unittests.py
